#!/bin/bash

if [ "$#" -lt 2 ]; then
	echo 'usage: certsafe WATERMARK IMAGE...'
	exit 1
fi

TEMP_DIR=$(mktemp -d)
mkdir -p out

watermark=$1
shift

if ! [[ -r $watermark ]]; then
	echo "$watermark not readable"
	exit 1
fi

for image in "$@"
do
	if ! [[ -r $image ]]; then
		echo "$image not readable, skipping"
		continue
	fi

	echo $image
	cp $image $TEMP_DIR
	image=$(basename $image)
	composite -dissolve 15 -tile $watermark $TEMP_DIR/$image $TEMP_DIR/$image
	mogrify -format jpg -resize 1024 $TEMP_DIR/$image
	image=$(echo "$image" | cut -f 1 -d '.')
	convert "$TEMP_DIR/$image.jpg" -density 50 "$TEMP_DIR/$image.pdf"
	mv $TEMP_DIR/$image.{jpg,pdf} out
done
echo 'done'

